### PR TITLE
Check for vertical chroma subsampling in get_pixel_data

### LINKED ISSUE #28: Frame::get_pixel_data is using wrong slice length?
I've noticed that the calculation for `plane_slice_length` on [this line](https://github.com/rust-av/ffms2-rs/blob/master/src/frame.rs#L211) doesn't seem to account for vertical subsampling (not sure what the actual term is, I'm new to this), causing the U and V plane slice lengths to be double of what they should be for `yuv420p` videos. `linesize` is correctly accounting for horizontal subsampling though.

As a workaround, on `yuv420p` videos I've been setting `linesize` for the U and V planes to half of what they should be:
```rust
frame.Linesize[1] /= 2;
frame.Linesize[2] /= 2;
```

### PR DESCRIPTION
**Pull request by ben476**
Fixes #28

### CODE REVIEW

File: src/frame.rs [hunk 1]
```diff
@@ -204,11 +206,18 @@ impl Frame {
         let mut data_vec = Vec::with_capacity(num_planes);
         let linesize = self.frame.Linesize;
 
+        // very sketchy, try to find a better way
+        let pix_fmt: AVPixelFormat =
+            unsafe { mem::transmute(self.frame.EncodedPixelFormat) };
+        let pix_fmt = Pixel::from(pix_fmt);
+        let log2_chroma_h = pix_fmt.descriptor().unwrap().log2_chroma_h();
```
Comment (Luni-4) [inline src/frame.rs]: Better `let log2_chroma_h = Pixel::from(pix_fmt).descriptor().unwrap().log2_chroma_h();`

Actually it would be better if `get_data` does not unwrap internally, perhaps we can have an API break and change the return type. What do you think?

File: src/frame.rs [hunk 2]
```diff
@@ -204,11 +206,18 @@ impl Frame {
...
+
         for i in 0..num_planes {
             if linesize[i] == 0 {
                 data_vec.push(None);
             } else {
-                let plane_slice_length = linesize[i] * frame_resolution.height;
+                let plane_slice_length = linesize[i] * frame_resolution.height
+                    / if i == 0 { 1 } else { 1 << log2_chroma_h };
```
Comment (Luni-4) [inline src/frame.rs]: We can use `EncodedHeight` as [here](https://github.com/FFMS/ffms2/blob/master/test/tests.cpp#L38) and let's put the `if` in another variable like the [example](https://github.com/FFMS/ffms2/blob/master/test/tests.cpp#L36)

File: src/frame.rs [hunk 3]
```diff
@@ -204,11 +206,18 @@ impl Frame {
         let mut data_vec = Vec::with_capacity(num_planes);
         let linesize = self.frame.Linesize;
 
+        // very sketchy, try to find a better way
+        let pix_fmt: AVPixelFormat =
+            unsafe { mem::transmute(self.frame.EncodedPixelFormat) };
```
Comment (Luni-4) [inline src/frame.rs:220]: This is bad, but I know there is not another method right now. The best way would be to add into `ffmpeg-the-third` a function to convert an `i32` into an enum, as explained in this blog post https://enodev.fr/posts/rusticity-convert-an-integer-to-an-enum.html

If you want you can try to open a PR upstream, better the first option to avoid dependencies in my opinion, a function like [this](https://github.com/shssoichiro/ffmpeg-the-third/blob/fe89e158c032b677ec83c1fcdfac9819c53e3918/src/util/format/pixel.rs#L434) for `i32`

**Review by Luni-4 — CHANGES_REQUESTED** [review]
Thanks a lot your your PR! :)

I guess we should change the `get_data` function such that it returns an error instead of unwrapping internally

**Comment by Luni-4** [comment]
We need to fix `clippy` errors and add missing `Frame` fields before though

File: src/frame.rs (hunk 1 above)
Comment (ben476) [reply src/frame.rs]: Yep, definitely sounds like a good idea.

In that case, I'll probably use `panic::catch_unwind` to catch the panic that happens in the default route for `Pixel::from` in case `pix_fmt` isn't a valid pixel format, and keep `pix_fmt` on its own line.

File: src/frame.rs (hunk 3 above)
Comment (ben476) [reply src/frame.rs:220]: That would be ideal. Would different enum definitions across different ffmpeg versions ([as FFMS2 API doc warns](https://github.com/FFMS/ffms2/blob/master/doc/ffms2-api.md#ffms_frame:~:text=It%20is%20strongly%20recommended%20to%20use%20this%20function%20instead%20of%20including%20pixfmt.h%20directly%2C%20since%20this%20function%20guarantees%20that%20you%20will%20always%20get%20the%20constant%20definitions%20from%20the%20version%20of%20FFmpeg%20that%20FFMS2%20was%20linked%20against.)) be an issue? I'm worried that conditions like [here](https://github.com/shssoichiro/ffmpeg-the-third/blob/fe89e158c032b677ec83c1fcdfac9819c53e3918/src/util/format/pixel.rs#L455) and [here](https://github.com/shssoichiro/ffmpeg-the-third/blob/fe89e158c032b677ec83c1fcdfac9819c53e3918/src/util/format/pixel.rs#L505) would cause i32 -> AVPixelFormat mappings to be inconsistent, which wouldn't be a problem with `mem::transmute` if we assume that ffmpeg-the-third and ffms2 use the same ffmpeg.

File: src/frame.rs (hunk 1 above)
Comment (Luni-4) [reply src/frame.rs]: If we don't enable [this](https://github.com/shssoichiro/ffmpeg-the-third/blob/fe89e158c032b677ec83c1fcdfac9819c53e3918/src/util/format/pixel.rs#L749) when we import the crate, it's not necessary `panic::catch_unwind` I guess

File: src/frame.rs (hunk 3 above)
Comment (Luni-4) [reply src/frame.rs:220]: Yep, you're right, but as it is now, this crate uses the last `ffms2` version, so an `ffmpeg` compatible with that version. Thus assuming that `ffmpeg-the-third` and `ffms2` have the same `ffmpeg` version is not wrong in my opinion. And a developer can re-build this crate setting up the correct `ffmpeg-the-third` version through features.

File: src/frame.rs (hunk 2 above)
Comment (Luni-4) [reply src/frame.rs]: We should copy the same code from the example in my opinion, so let's use right shifts instead of divisions

Comment (ben476) [reply src/frame.rs]: TIL right shifts :)

File: src/frame.rs (hunk 1 above)
Comment (ben476) [reply src/frame.rs]: Ohh right. I'm pretty new to Rust, so wasn't sure how that attribute worked.

File: src/frame.rs (hunk 3 above)
Comment (ben476) [reply src/frame.rs:220]: So if a match statement for example 
```rust
match {
    1 => Pixel::YUV422P16BE
    2 => Pixel::YUV444P16BE,
    #[cfg(feature = "ff_api_vdpau")]
    3 => Pixel::VDPAU_MPEG4,
    4 => Pixel::DXVA2_VLD,
}
```
were in `ffmpeg-the-third`, would it still be valid regardless of `ff_api_vdpau` being enabled in `ffmpeg`? 
So if `ff_api_vdpau` was disabled, would `Pixel::DXVA2_VLD` still be 4, or should it actually be 3?

Comment (Luni-4) [reply src/frame.rs:220]: If `ff_api_vdpau` feature is enabled, `Pixel::DXVA2_VLD` remains 4. If it's disabled, it remains 4 the same. Practically a feature adds and removes line/s

File: src/frame.rs (hunk 1 above)
Comment (Luni-4) [reply src/frame.rs]: No problem :)

File: src/frame.rs [hunk 4]
```diff
@@ -199,25 +200,38 @@ impl Frame {
         FrameResolution { width, height }
     }
 
-    pub fn get_pixel_data(&self) -> Vec<Option<&[u8]>> {
+    pub fn get_pixel_data(&self) -> Result<Vec<Option<&[u8]>>, String> {
```
Comment (Luni-4) [inline src/frame.rs]: Perhaps we can return an Option instead of a Result, like we do for `descriptor`

In this way we tell a developer that there are no data currently available. If we prefer a Result, we can use [Errors](https://github.com/rust-av/ffms2-rs/blob/master/src/lib.rs#L22) instead of a String. [Here](https://github.com/rust-av/ffms2-rs/blob/423429eece9ebb8b5b879e8bad19c2653e9f5edd/src/index.rs) you can find some examples for its usage

**Review by Luni-4 — CHANGES_REQUESTED** [review]

File: src/frame.rs (hunk 3 above)
Comment (ben476) [reply src/frame.rs:220]: Oh, I should've been more clear. So [here in the `ffmpeg` source](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/pixfmt.h#L291), if the flag is disabled, all the enum values after that would have their underlying `int` representation (which `FFMS_GetPixFmt` returns) reduced by one, and therefore invalidate a hardcoded match statement to convert `i32` -> `AVPixelFormat`.

So in my previous message, if `ff_api_vdpau` was disabled in both `ffmpeg-the-third` and `ffmpeg`, would that mean 4 being mapped to `Pixel::DXVA2_VLD` is incorrect, and should somehow be the mapping for 3 instead? Similarly, all the following mapping would need to change as well.

File: src/frame.rs (hunk 4 above)
Comment (ben476) [reply src/frame.rs]: Thanks! I'm learning quite a lot from this.

Sorry for being a bit of a noob :)

Comment (Luni-4) [reply src/frame.rs]: Thanks to you, you're doing great! :) 

No problem!

File: src/frame.rs (hunk 3 above)
Comment (Luni-4) [reply src/frame.rs:220]: @shssoichiro Could you help us to unravel the tangle?

Comment (Luni-4) [reply src/frame.rs:220]: @ben476 

Perhaps we can tackle this problem using the value of the `XVMC` field. Since it's the only preprocessor flags in `ffmpeg` we can adopt this condition.

```
if xmvc_value == "value with flags disabled" and my_enum_value > xmvc_value {
   return my_enum_value - 1
}
```
Practically we assume that the flags is always enabled. But I guess this matter should be discussed on `ffmpeg-the-third` in an apposite PR

Comment (shssoichiro) [reply src/frame.rs:220]: As with anything in ffmpeg, this seems to be a shortcoming of the ffmpeg API. This was not thought through when they implemented it.

The above suggestion is probably the best option @Luni-4 unfortunately...

Comment (Luni-4) [reply src/frame.rs:220]: I agree and it should fix the problem. What do you think @ben476?

Comment (ben476) [reply src/frame.rs:220]: I'm not too sure... Previous versions of `ffmpeg` have different flag checks and have also removed flags from the middle of the enum, such as [here](https://github.com/FFmpeg/FFmpeg/commit/ad524cb9eeb298f7a60d923094fbebb1fda7e0e3)

It seems like you would need to check a lot more flags, as well as the `ffmpeg` version.

Comment (Luni-4) [reply src/frame.rs:220]: If we decide to consider more versions, we need to support all flags of each of the considered version. So we need to add more checks and enable/disable them through rust features

Comment (ben476) [reply src/frame.rs:220]: Is `transmute` still an option? Maybe making a PR in `ffms2` to expose chroma height in the frame struct would be a better option at this point

Comment (Luni-4) [reply src/frame.rs:220]: Yeah, I agree with you. Let's keep the `transmute` option for now, but please write as comment over that line of code  all possible solutions we have thought of here. And a PR in `ffms2` would be great.

Could you also update `ffms2-rs` to last `ffms2` version and fix clippy lints in another PR, too? So we will fix CI too

Comment (ben476) [reply src/frame.rs:220]: Cool, I'm happy to do that comment. I'm quite busy from now on, so I won't be able to work on the PRs for a while, but I'll make sure to get to it when I have the chance.

Comment (shssoichiro) [reply src/frame.rs:220]: In fact given the fact that this isn't the only case where this happens in ffmpeg's enums, it might be better to consider a solution that doesn't involve converting the enums to/from an integer, if it's possible to convert to the enum from its stringified name instead perhaps?

Comment (ben476) [reply src/frame.rs:220]: That would be perfect, but it doesn't seem that FFMS2 provides a function to convert the integer identifier (which we have) to a name, despite there being a function for the other way around.

Comment (Luni-4) [reply src/frame.rs:220]: For now let's land this PR, waiting for a solution upstream in `ffmpeg-the-third`
